on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-18.04
    name: Test the action YAML
    steps:
      - uses: actions/checkout@master
      - name: Use the action YAML
        uses: ./
        with:
          branch: master
      - name: Get Java and maven version
        run: |
          java -version
          mvn -version
